FROM rust:1.84 as builder
WORKDIR /app
COPY . .

RUN cargo build --release

FROM debian:bookworm-slim
WORKDIR /app
RUN apt-get update && apt-get install -y libssl-dev ca-certificates && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/release/ghost_api /app/ghost_api

EXPOSE 8080
CMD ["./ghost_api"]

